# Change these first
owner: teledec # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: STAC endpoint
    url: https://api.stac.teledetection.fr
  - name: STAC endpoint for QGIS
    url: https://qgis.stac.teledetection.fr
  - name: STAC browser
    url: https://browser.stac.teledetection.fr
  - name: URL signing
    url: https://signing.stac.teledetection.fr/docs
  - name: Home
    url: https://www.stac.teledetection.fr
  - name: API key management
    url: https://gate.stac.teledetection.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://www.stac.teledetection.fr/images/mtd.svg
  name: Teledetection up time
  introTitle: "**Teledetection** uptime monitor and status page."
  introMessage: Summary of active and inactive web services provided by the [Teledetection geospatial data infrastructure](https://www.stac.teledetection.fr).
  navbar:
    - title: Home
      href: https://www.stac.teledetection.fr/en/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
